services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Brotkrueml\MatomoIntegration\:
    resource: '../Classes/*'

  Brotkrueml\MatomoIntegration\Domain\TrackingCode\JavaScriptTrackingCodeBuilder:
    public: true

  Brotkrueml\MatomoIntegration\Domain\TrackingCode\NoScriptTrackingCodeBuilder:
    public: true
