services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Brotkrueml\MatomoIntegration\:
    resource: '../Classes/*'

  Brotkrueml\MatomoIntegration\Code\JavaScriptTrackingCodeBuilder:
    public: true

  Brotkrueml\MatomoIntegration\Code\NoScriptTrackingCodeBuilder:
    public: true

  Brotkrueml\MatomoIntegration\Code\TagManagerCodeBuilder:
    public: true
